//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaMent_v2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CONTENTTABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTENTTABLE()
        {
            this.CONTENTROLEs = new HashSet<CONTENTROLE>();
        }
    
        public int CONTENTID { get; set; }
        public int USERID { get; set; }
        public int STATUSID { get; set; }
        public int CONTENTTYPEID { get; set; }
        [Required]
        [Display(Name = "Content Title")]
        public string CONTENTTITLE { get; set; }
        [Required]
        [Display(Name = "Content Description")]
        public string CONTENTDESCRIPTION { get; set; }
        [Display(Name = "Content Link")]
        public string CONTENTLINK { get; set; }
        [Display(Name = "Content File")]
        public string CONTENTFILEPATH { get; set; }
        [Display(Name = "Content Date")]
        public System.DateTime CONTENTDATE { get; set; }
        [Display(Name = "Content Keyword")]
        public string CONTENTKEYWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTENTROLE> CONTENTROLEs { get; set; }
        public virtual CONTENTTYPETABLE CONTENTTYPETABLE { get; set; }
        public virtual STATUSTABLE STATUSTABLE { get; set; }
    }
}
