//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaMent_v2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CONTENTTYPETABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTENTTYPETABLE()
        {
            this.CONTENTTABLEs = new HashSet<CONTENTTABLE>();
        }
    
        public int CONTENTTYPEID { get; set; }
        public int STATUSID { get; set; }
        [Required]
        [Display(Name = "Content Type Name")]
        public string CONTENTTYPENAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTENTTABLE> CONTENTTABLEs { get; set; }
        public virtual STATUSTABLE STATUSTABLE { get; set; }
    }
}
