//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaMent_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENTROLE
    {
        public int CONTENTROLEID { get; set; }
        public Nullable<int> ROLEID { get; set; }
        public Nullable<int> CONTENTID { get; set; }
    
        public virtual CONTENTTABLE CONTENTTABLE { get; set; }
        public virtual ROLETABLE ROLETABLE { get; set; }
    }
}
