//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaMent_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaMent_DB_v2Entities : DbContext
    {
        public MaMent_DB_v2Entities()
            : base("name=MaMent_DB_v2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTENTROLE> CONTENTROLEs { get; set; }
        public virtual DbSet<CONTENTTABLE> CONTENTTABLEs { get; set; }
        public virtual DbSet<CONTENTTYPETABLE> CONTENTTYPETABLEs { get; set; }
        public virtual DbSet<ROLETABLE> ROLETABLEs { get; set; }
        public virtual DbSet<STATUSTABLE> STATUSTABLEs { get; set; }
        public virtual DbSet<USERROLE> USERROLEs { get; set; }
        public virtual DbSet<USERTABLE> USERTABLEs { get; set; }
    }
}
