//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaMent_v2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ROLETABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLETABLE()
        {
            this.CONTENTROLEs = new HashSet<CONTENTROLE>();
        }
    
        public int ROLEID { get; set; }
        public int STATUSID { get; set; }
        [Required]
        [Display(Name = "Role Name")]
        public string ROLENAME { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Role Description")]
        public string ROLEDESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTENTROLE> CONTENTROLEs { get; set; }
        public virtual STATUSTABLE STATUSTABLE { get; set; }
    }
}
