//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaMent_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUSTABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATUSTABLE()
        {
            this.CONTENTTABLEs = new HashSet<CONTENTTABLE>();
            this.CONTENTTYPETABLEs = new HashSet<CONTENTTYPETABLE>();
            this.ROLETABLEs = new HashSet<ROLETABLE>();
            this.USERTABLEs = new HashSet<USERTABLE>();
        }
    
        public int STATUSID { get; set; }
        public string STATUSNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTENTTABLE> CONTENTTABLEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTENTTYPETABLE> CONTENTTYPETABLEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLETABLE> ROLETABLEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTABLE> USERTABLEs { get; set; }
    }
}
