//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaMent_v2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USERTABLE
    {
        public int USERID { get; set; }
        public int STATUSID { get; set; }
        [Display(Name = " Username")]
        public string USERNAME { get; set; }
        [Display(Name = " Password")]
        public string USERPASSWORD { get; set; }
        public virtual STATUSTABLE STATUSTABLE { get; set; }
    }
}
